#!/usr/bin/env python

# **************************************************************************************
# 			                      ______
# 			                   .-"      "-.
# 			                  /    SSH     \
# 			                 |              |
# 			                 |,  .-.  .-.  ,|
# 			                 | )(__/  \__)( |
# 			                 |/     /\     \|
# 			       (@_       (_     ^^     _)
# 			  _     ) \_______\__|IIIIII|__/__________________________
# 			 (_)@8@8{}<________|-\IIIIII/-|___________________________>
# 			        )_/        \          /
# 			       (@           `--------`                    
#
# **************************************************************************************

#
import glob
import os.path
import sys,os,string
import commands
#
import smtplib 
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase 
from smtplib import SMTP, quotedata, CRLF, SMTPDataError  
from email import Encoders  

def main( argv ):
	print ("execute post-receive -----> "+sys.argv[0])
	sys.exit(0)

if __name__ == '__main__' :
	sys.exit(main(sys.argv))

