#!/usr/bin/env python

# **************************************************************************************
# 			                      ______
# 			                   .-"      "-.
# 			                  /    SSH     \
# 			                 |              |
# 			                 |,  .-.  .-.  ,|
# 			                 | )(__/  \__)( |
# 			                 |/     /\     \|
# 			       (@_       (_     ^^     _)
# 			  _     ) \_______\__|IIIIII|__/__________________________
# 			 (_)@8@8{}<________|-\IIIIII/-|___________________________>
# 			        )_/        \          /
# 			       (@           `--------`                    
#
# **************************************************************************************

import glob
import os.path
import sys,os,string
import commands
from subprocess import call
from sys import stdin

import smtplib 
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase 
from smtplib import SMTP, quotedata, CRLF, SMTPDataError  
from email import Encoders  

from subprocess import call

def main( argv ):
	print ("\n========================================hook script " + sys.argv[0])
	
	#status,output = commands.getstatusoutput('rm -rv foo.*')
	status,output = commands.getstatusoutput('git diff HEAD > foo.diff;cat foo.diff | python ./tools/diff2html.py > foo.html')

	sys.exit(0)

if __name__ == '__main__' :
	sys.exit(main(sys.argv))