#!/usr/bin/env python

# **************************************************************************************
# 			                      ______
# 			                   .-"      "-.
# 			                  /    SSH     \
# 			                 |              |
# 			                 |,  .-.  .-.  ,|
# 			                 | )(__/  \__)( |
# 			                 |/     /\     \|
# 			       (@_       (_     ^^     _)
# 			  _     ) \_______\__|IIIIII|__/__________________________
# 			 (_)@8@8{}<________|-\IIIIII/-|___________________________>
# 			        )_/        \          /
# 			       (@           `--------`                    
#
# **************************************************************************************

import glob
import os.path
import sys,os,string
import commands
from subprocess import call
from sys import stdin

from subprocess import call

def main( argv ):
	print ("\n========================================hook script " + sys.argv[0])
	

	sys.exit(0)

if __name__ == '__main__' :
	sys.exit(main(sys.argv))

